version: '2'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5552:5552'
      - '5672:5672'
      - '15672:15672'
      - '1883:1883'
      - '61613:61613'
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS= -rabbitmq_stream advertised_host localhost
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
